CREATE TABLE library.app_user
(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE library.book
(
    ID BIGINT NOT NULL PRIMARY KEY,
    TITLE CHARACTER VARYING(255) NOT NULL,
    AUTHOR CHARACTER VARYING(255) NOT NULL,
    IS_BORROWED BOOLEAN NOT NULL,
    APP_USER_ID BIGINT NOT NULL REFERENCES library.app_user(ID)
);

CREATE SEQUENCE library.app_user_seq
    INCREMENT 1
    START 1000;

CREATE SEQUENCE library.book_seq
    INCREMENT 1
    START 1000