CREATE TABLE library.user
(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE library.book
(
    ID BIGINT NOT NULL PRIMARY KEY,
    TITLE CHARACTER VARYING(255) NOT NULL,
    AUTHOR CHARACTER VARYING(255) NOT NULL,
    IS_BORROWED BOOLEAN NOT NULL,
    USER_ID BIGINT NOT NULL REFERENCES library.user(ID)
);

CREATE SEQUENCE library.user_seq
    INCREMENT 1
    START 1000;

CREATE SEQUENCE library.book_seq
    INCREMENT 1
    START 1000